# -*- coding: utf-8 -*-
"""Damped spring-mass oscillator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OLpTPevX0DVz9xjCEOPc5A3jXUqI3WLB

*Rendimiento de Muestra: Polinomio Interpolador*
"""



#@title Implementación en Python
import numpy as np
import matplotlib.pyplot as plt
from math import pi

#Función de base cuadrática de Lagrange P2 en referenfcia [0,1]
def phi_ref(xi):
  return np.array([
      (xi-1)*(2*xi-1),
      4*xi*(1-xi),
      xi*(2*xi - 1)
  ])

#Derivada
def dphi_ref(xi):
  return np.array([
      4*xi -3,
      4-8*xi,
      4*xi -1
  ])


#vector de carga y matriz de rigidez
def ensambla_p2(N, f):
  h = 1.0 / N              # Paso
  M = 2 * N + 1    # Número de nodos
  x = np.linspace(0, 1, M) # Nodos globales (paso h/2)
  K = np.zeros((M, M)) # Matriz de rigidez global
  F = np.zeros(M)  # Vector de carga global

  # Cuadratura de Gauss (3 puntos en [0,1])
  xi_g = np.array([0.5 - np.sqrt(3/5)/2, 0.5, 0.5 + np.sqrt(3/5)/2])
  w_g  = np.array([5/18, 8/18, 5/18])


    # Integración numérica
    for k in range(3):
      xi = xi_g[k]
      w  = w_g[k]
      dph = dphi_ref(xi)
      ph = phi_ref(xi)
      x_phys = x0 + h * xi

      # Integrales locales
      ke += np.outer(dph, dph) * (w / h)
      Fe += ph * f(x_phys) * w * h

    # Ensamblaje global


  return K, F, x



#@title Aplicando el ejemplo a $f(x) = \pi^{2} \sin(\pi x)$ y $u(x) = \sin(\pi x)$
def f(x):
  """Función fuente"""
  return (pi**2) * np.sin(pi * x)

# Número de elementos
N = 10

# Ensamblar el sistema
K, F, x_nodes = ensambla_p2(N, f)

# Aplicar condiciones de contorno homogéneas
M = len(x_nodes)
free = np.arange(1, M - 1)
K_ff = K[np.ix_(free, free)]
F_f  = F[free]

# Resolver el sistema lineal
u = np.zeros(M)
u[free] = np.linalg.solve(K_ff, F_f)

# Solución exacta
u_exact = np.sin(pi * x_nodes)

#@title Imprime resultado y Grafica